In [5]:
import numpy as np

In [6]:
M = np.array([[2,1,1], [1,2,1], [1,1,2]]) #Criando a matriz
D = np.linalg.det(M) #Claculando o determinante
print(D)

3.999999999999999


## Classificação dos

In [130]:
A = np.array([[1,1], [-3,1]])
B = np.array([6,2])#Matriz dos termos independentes
Ax = np.array([[6,1], [2,1]]) #Troca os elemenos da coluna x pelos termos independetes
detA = np.linalg.det(A) #determinante da matriz A
detAx = np.linalg.det(Ax)  #determinante da matriz Ax
A

array([[ 1,  1],
       [-3,  1]])

In [17]:
A = np.array([[1,4,7], [2,3,6], [5,1,-1]])
B = np.array([2,2,8])
Ax = np.array([[2,4,7], [2,3,6], [8,1,-1]]) #Troca os elemenos da coluna x pelos termos independetes
detA = np.linalg.det(A) #determinante da matriz A
detAx = np.linalg.det(Ax)  #determinante da matriz Ax
Ax

array([[ 2,  4,  7],
       [ 2,  3,  6],
       [ 8,  1, -1]])

In [18]:
#analisar o determinante
if detA !=0:
    S = np.linalg.solve(A, B)
    print(f'SPD e asolução é {S}')
else:
    if detA == 0 and detAx == 0:
        print('SPI')
    else:
        print('SI')

SPD e asolução é [ 1.  2. -1.]


In [7]:
#analisar o determinante

def swap(a, b):
    x = a.copy()
    y = b.copy()
    x[:, 0] = y
    return x

def analisa_determinan(a,b):
    Ax = swap(a, b)
    detA = np.linalg.det(A)
    detAx = np.linalg.det(Ax)  
    if detA !=0:
        S = np.linalg.solve(A, B)
        print(f'SPD e asolução é {S}')
    else:
        if detA == 0 and detAx == 0:
            print('SPI')
        else:
            print('SI')

In [8]:
A = np.array([[2, -1], [1, 5]])
B = np.array([7, -2])
analisa_determinan(A,B)

SPD e asolução é [ 3. -1.]


In [20]:
A = np.array([[1, 2, -1],[3, -4, 5], [1, 1, 9]])
B = np.array([0, 10, 1])
analisa_determinan(A,B)

SPD e asolução é [ 2.00000000e+00 -1.00000000e+00 -6.43607551e-18]


In [11]:
A = np.array([[1,4,7], [2,3,6], [5,1,-1]])
B = np.array([2,2,8])
analisa_determinan(A,B)

SPD e asolução é [ 1.  2. -1.]


In [13]:
A = np.array([[1,1,1,1], [-1, 2, 1,0], [2,-1,-1,-1], [1,-3,1,2]])
B = np.array([1,2,-1,0])
analisa_determinan(A,B)

SPD e asolução é [-8.88178420e-17 -1.77635684e-16  2.00000000e+00 -1.00000000e+00]


In [154]:
analisa_determinan(A,B)

SPD e asolução é [-8.88178420e-17 -1.77635684e-16  2.00000000e+00 -1.00000000e+00]


In [156]:
S = np.linalg.solve(A, B)
S

array([-8.88178420e-17, -1.77635684e-16,  2.00000000e+00, -1.00000000e+00])

In [75]:
df = pd.DataFrame(A)
df.set_index(0, inplace=True)